version: "3.9"

services:

  web:
    image: "nginx"
    volumes:
      - ./www:/var/www
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    hostname: nginx
    networks:
      - net
    ports:
      - "127.0.0.1:80:80"
    links:
      - php

  php:
    build: .
    networks:
      - net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://nginx | grep works"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./www:/var/www

networks:
  net: